Models/Respuesta.cs
using System.ComponentModel.DataAnnotations;

namespace ORT_PNT1_Proyecto_2022_2C_I_Foro.Models{
    public class Respuesta {
        public int RespuestaId { get; set; }
        [DataType(DataType.Date)]
        public DateTime Fecha { get; set; }
        public string Descripcion { get; set; }
        [Display(Name = "Likes")]
        public int CantMeGustas { get; set; }
        public int MiembroId { get; set; }
        public Miembro Miembro { get; set; }
        public int PreguntaId { get; set; }
        public Pregunta Pregunta { get; set; }

    }
}

Controllers/PreguntasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ORT_PNT1_Proyecto_2022_2C_I_Foro.Data;
using ORT_PNT1_Proyecto_2022_2C_I_Foro.Models;

namespace ORT_PNT1_Proyecto_2022_2C_I_Foro.Controllers
{
    public class PreguntasController : Controller
    {
        private readonly ForoContext _context;

        public PreguntasController(ForoContext context)
        {
            _context = context;
        }

        // GET: Preguntas
        public async Task<IActionResult> Index()
        {
            var foroContext = _context.Preguntas.Include(p => p.Miembro);
            return View(await foroContext.ToListAsync());
        }

        // GET: Preguntas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Preguntas == null)
            {
                return NotFound();
            }

            var pregunta = await _context.Preguntas
                .Include(p => p.Miembro)
                .Include(p => p.Respuestas)
                .ThenInclude(r => r.Miembro)
                .AsNoTracking()
                .FirstOrDefaultAsync(m => m.PreguntaId == id);

            if (pregunta == null)
            {
                return NotFound();
            }

            return View(pregunta);
        }

        // GET: Preguntas/Create
        public IActionResult Create()
        {
            ViewData["MiembroId"] = new SelectList(_context.Miembros, "MiembroId", "MiembroId");
            return View();
        }

        // POST: Preguntas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Titulo,Descripcion")] Pregunta pregunta)
        {
            pregunta.Fecha = DateTime.Now;
            pregunta.CantMeGustas = 0;
            if(HttpContext.Session.GetInt32("_MiembroId") == null)
            {
                return Redirect("/home/customerror");
            }
            pregunta.MiembroId = (int)HttpContext.Session.GetInt32("_MiembroId");
            if (ModelState.IsValid)
            {
                _context.Add(pregunta);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            //ViewData["MiembroId"] = new SelectList(_context.Miembros, "MiembroId", "MiembroId", pregunta.MiembroId);
            return View(pregunta);
        }

        // GET: Preguntas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Preguntas == null)
            {
                return NotFound();
            }

            var pregunta = await _context.Preguntas
                .Include(p => p.Miembro)
                .FirstOrDefaultAsync(m => m.PreguntaId == id);
            if (pregunta == null)
            {
                return NotFound();
            }

            return View(pregunta);
        }

        // POST: Preguntas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Preguntas == null)
            {
                return Problem("Entity set 'ForoContext.Preguntas'  is null.");
            }
            var pregunta = await _context.Preguntas.FindAsync(id);
            if (pregunta != null)
            {
                _context.Preguntas.Remove(pregunta);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PreguntaExists(int id)
        {
          return _context.Preguntas.Any(e => e.PreguntaId == id);
        }
    }
}

Controllers/RespuestasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ORT_PNT1_Proyecto_2022_2C_I_Foro.Data;
using ORT_PNT1_Proyecto_2022_2C_I_Foro.Models;

namespace ORT_PNT1_Proyecto_2022_2C_I_Foro.Controllers
{
    public class RespuestasController : Controller
    {
        private readonly ForoContext _context;

        public RespuestasController(ForoContext context)
        {
            _context = context;
        }

        // GET: Respuestas
        public async Task<IActionResult> Index()
        {
            var foroContext = _context.Respuestas.Include(r => r.Miembro).Include(r => r.Pregunta);
            return View(await foroContext.ToListAsync());
        }

        // GET: Respuestas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Respuestas == null)
            {
                return NotFound();
            }

            var respuesta = await _context.Respuestas
                .Include(r => r.Miembro)
                .Include(r => r.Pregunta)
                .FirstOrDefaultAsync(m => m.RespuestaId == id);
            if (respuesta == null)
            {
                return NotFound();
            }

            return View(respuesta);
        }

        // GET: Respuestas/Create
        public IActionResult Create(int preguntaId, string titulo)
        {
            ViewData["PreguntaId"] = preguntaId;
            ViewData["Titulo"] = titulo;
            return View();
        }

        // POST: Respuestas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Descripcion, PreguntaId")] Respuesta respuesta)
        {
            //RespuestaId,Fecha,CantMeGustas,MiembroId,PreguntaId
            respuesta.Fecha = DateTime.Now;
            respuesta.CantMeGustas = 0;
            if (HttpContext.Session.GetInt32("_MiembroId") == null)
            {
                return Redirect("/home/customerror");
            }
            respuesta.MiembroId = (int)HttpContext.Session.GetInt32("_MiembroId");
            if (ModelState.IsValid)
            {
                _context.Add(respuesta);
                await _context.SaveChangesAsync();
                return Redirect($"/preguntas/details/{respuesta.PreguntaId}");
            }
            //ViewData["MiembroId"] = new SelectList(_context.Miembros, "MiembroId", "MiembroId", respuesta.MiembroId);
            //ViewData["PreguntaId"] = new SelectList(_context.Preguntas, "PreguntaId", "PreguntaId", respuesta.PreguntaId);
            return View(respuesta);
        }

        // GET: Respuestas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Respuestas == null)
            {
                return NotFound();
            }

            var respuesta = await _context.Respuestas
                .Include(r => r.Miembro)
                .Include(r => r.Pregunta)
                .FirstOrDefaultAsync(m => m.RespuestaId == id);
            if (respuesta == null)
            {
                return NotFound();
            }

            return View(respuesta);
        }

        // POST: Respuestas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Respuestas == null)
            {
                return Problem("Entity set 'ForoContext.Respuestas'  is null.");
            }
            var respuesta = await _context.Respuestas.FindAsync(id);
            if (respuesta != null)
            {
                _context.Respuestas.Remove(respuesta);
            }
            
            await _context.SaveChangesAsync();
            return Redirect($"/preguntas/details/{respuesta.PreguntaId}");
        }

        private bool RespuestaExists(int id)
        {
          return _context.Respuestas.Any(e => e.RespuestaId == id);
        }
    }
}

Views/Respuestas/Create.cshtml
@model ORT_PNT1_Proyecto_2022_2C_I_Foro.Models.Respuesta

@{
    ViewData["Title"] = "Agregar Respuesta";
}

<h1>Agregar Respuesta</h1>

<h4>Responder a: @ViewData["Titulo"]</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @*<div class="form-group">
                <label asp-for="Fecha" class="control-label"></label>
                <input asp-for="Fecha" class="form-control" />
                <span asp-validation-for="Fecha" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <label asp-for="Descripcion" class="control-label"></label>
                <textarea asp-for="Descripcion" class="form-control" style="resize:none;" rows="5"></textarea>
                <span asp-validation-for="Descripcion" class="text-danger"></span>
            </div>
            @*<div class="form-group">
                <label asp-for="CantMeGustas" class="control-label"></label>
                <input asp-for="CantMeGustas" class="form-control" />
                <span asp-validation-for="CantMeGustas" class="text-danger"></span>
            </div>*@
            @*<div class="form-group">
                <label asp-for="MiembroId" class="control-label"></label>
                <select asp-for="MiembroId" class ="form-control" asp-items="ViewBag.MiembroId"></select>
            </div>*@
            @*<div class="form-group">
                <label asp-for="PreguntaId" class="control-label"></label>
                <select asp-for="PreguntaId" class ="form-control" asp-items="ViewBag.PreguntaId"></select>
            </div>*@
            <div class="form-group" style="display:none;">
                <label asp-for="PreguntaId" class="control-label">Id Pregunta</label>
                <input asp-for="PreguntaId" class="form-control" value="@ViewData["PreguntaId"]" />
            </div>
            <div class="form-group">
                <input type="submit" value="Agregar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-controller="Preguntas" asp-action="Details" asp-route-id="@ViewData["PreguntaId"]">Volver</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Respuestas/Delete.cshtml
@model ORT_PNT1_Proyecto_2022_2C_I_Foro.Models.Respuesta

@{
    ViewData["Title"] = "Borrar";
}

<h1>Borrar</h1>

<h3>Seguro que quieres borrar esto?</h3>
<div>
    <h4>Respuesta</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Fecha)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Fecha)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Descripcion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CantMeGustas)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CantMeGustas)
        </dd>
        <dt class = "col-sm-2">
            Id Miembro
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Miembro.MiembroId)
        </dd>
        <dt class = "col-sm-2">
            Id Pregunta
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Pregunta.PreguntaId)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="RespuestaId" />
        <input type="submit" value="Borrar" class="btn btn-danger" /> |
        <a asp-action="Details" asp-controller="Preguntas" asp-route-id="@Model.Pregunta.PreguntaId">Volver</a>
    </form>
</div>

Views/Respuestas/Details.cshtml
@model ORT_PNT1_Proyecto_2022_2C_I_Foro.Models.Respuesta

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Respuesta</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Fecha)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Fecha)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Descripcion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CantMeGustas)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CantMeGustas)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Miembro)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Miembro.MiembroId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Pregunta)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Pregunta.PreguntaId)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.RespuestaId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Respuestas/Index.cshtml
@model IEnumerable<ORT_PNT1_Proyecto_2022_2C_I_Foro.Models.Respuesta>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Fecha)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Descripcion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CantMeGustas)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Miembro)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Pregunta)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Fecha)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Descripcion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CantMeGustas)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Miembro.MiembroId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Pregunta.PreguntaId)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.RespuestaId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.RespuestaId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.RespuestaId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>