Models/Pregunta.cs
using System.ComponentModel.DataAnnotations;
using System.Diagnostics.CodeAnalysis;

namespace ORT_PNT1_Proyecto_2022_2C_I_Foro.Models{
    public class Pregunta  {
        public int PreguntaId { get; set; }
        [DataType(DataType.Date)]
        public DateTime Fecha { get; set; }
        public string Titulo { get; set; }
        public string Descripcion { get; set; }
        [Display(Name = "Likes")]
        public int CantMeGustas { get; set; }
        public int MiembroId { get; set; }
        public Miembro Miembro { get; set; }
        public ICollection<Respuesta> Respuestas { get; set; }
        public ICollection<Categoria> Categorias { get; set; }

        


    }
}

Controllers/PreguntasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ORT_PNT1_Proyecto_2022_2C_I_Foro.Data;
using ORT_PNT1_Proyecto_2022_2C_I_Foro.Models;

namespace ORT_PNT1_Proyecto_2022_2C_I_Foro.Controllers
{
    public class PreguntasController : Controller
    {
        private readonly ForoContext _context;

        public PreguntasController(ForoContext context)
        {
            _context = context;
        }

        // GET: Preguntas
        public async Task<IActionResult> Index()
        {
            var foroContext = _context.Preguntas.Include(p => p.Miembro);
            return View(await foroContext.ToListAsync());
        }

        // GET: Preguntas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Preguntas == null)
            {
                return NotFound();
            }

            var pregunta = await _context.Preguntas
                .Include(p => p.Miembro)
                .Include(p => p.Respuestas)
                .ThenInclude(r => r.Miembro)
                .AsNoTracking()
                .FirstOrDefaultAsync(m => m.PreguntaId == id);

            if (pregunta == null)
            {
                return NotFound();
            }

            return View(pregunta);
        }

        // GET: Preguntas/Create
        public IActionResult Create()
        {
            ViewData["MiembroId"] = new SelectList(_context.Miembros, "MiembroId", "MiembroId");
            return View();
        }

        // POST: Preguntas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Titulo,Descripcion")] Pregunta pregunta)
        {
            pregunta.Fecha = DateTime.Now;
            pregunta.CantMeGustas = 0;
            if(HttpContext.Session.GetInt32("_MiembroId") == null)
            {
                return Redirect("/home/customerror");
            }
            pregunta.MiembroId = (int)HttpContext.Session.GetInt32("_MiembroId");
            if (ModelState.IsValid)
            {
                _context.Add(pregunta);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            //ViewData["MiembroId"] = new SelectList(_context.Miembros, "MiembroId", "MiembroId", pregunta.MiembroId);
            return View(pregunta);
        }

        // GET: Preguntas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Preguntas == null)
            {
                return NotFound();
            }

            var pregunta = await _context.Preguntas
                .Include(p => p.Miembro)
                .FirstOrDefaultAsync(m => m.PreguntaId == id);
            if (pregunta == null)
            {
                return NotFound();
            }

            return View(pregunta);
        }

        // POST: Preguntas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Preguntas == null)
            {
                return Problem("Entity set 'ForoContext.Preguntas'  is null.");
            }
            var pregunta = await _context.Preguntas.FindAsync(id);
            if (pregunta != null)
            {
                _context.Preguntas.Remove(pregunta);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PreguntaExists(int id)
        {
          return _context.Preguntas.Any(e => e.PreguntaId == id);
        }
    }
}

Controllers/RespuestasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ORT_PNT1_Proyecto_2022_2C_I_Foro.Data;
using ORT_PNT1_Proyecto_2022_2C_I_Foro.Models;

namespace ORT_PNT1_Proyecto_2022_2C_I_Foro.Controllers
{
    public class RespuestasController : Controller
    {
        private readonly ForoContext _context;

        public RespuestasController(ForoContext context)
        {
            _context = context;
        }

        // GET: Respuestas
        public async Task<IActionResult> Index()
        {
            var foroContext = _context.Respuestas.Include(r => r.Miembro).Include(r => r.Pregunta);
            return View(await foroContext.ToListAsync());
        }

        // GET: Respuestas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Respuestas == null)
            {
                return NotFound();
            }

            var respuesta = await _context.Respuestas
                .Include(r => r.Miembro)
                .Include(r => r.Pregunta)
                .FirstOrDefaultAsync(m => m.RespuestaId == id);
            if (respuesta == null)
            {
                return NotFound();
            }

            return View(respuesta);
        }

        // GET: Respuestas/Create
        public IActionResult Create(int preguntaId, string titulo)
        {
            ViewData["PreguntaId"] = preguntaId;
            ViewData["Titulo"] = titulo;
            return View();
        }

        // POST: Respuestas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Descripcion, PreguntaId")] Respuesta respuesta)
        {
            //RespuestaId,Fecha,CantMeGustas,MiembroId,PreguntaId
            respuesta.Fecha = DateTime.Now;
            respuesta.CantMeGustas = 0;
            if (HttpContext.Session.GetInt32("_MiembroId") == null)
            {
                return Redirect("/home/customerror");
            }
            respuesta.MiembroId = (int)HttpContext.Session.GetInt32("_MiembroId");
            if (ModelState.IsValid)
            {
                _context.Add(respuesta);
                await _context.SaveChangesAsync();
                return Redirect($"/preguntas/details/{respuesta.PreguntaId}");
            }
            //ViewData["MiembroId"] = new SelectList(_context.Miembros, "MiembroId", "MiembroId", respuesta.MiembroId);
            //ViewData["PreguntaId"] = new SelectList(_context.Preguntas, "PreguntaId", "PreguntaId", respuesta.PreguntaId);
            return View(respuesta);
        }

        // GET: Respuestas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Respuestas == null)
            {
                return NotFound();
            }

            var respuesta = await _context.Respuestas
                .Include(r => r.Miembro)
                .Include(r => r.Pregunta)
                .FirstOrDefaultAsync(m => m.RespuestaId == id);
            if (respuesta == null)
            {
                return NotFound();
            }

            return View(respuesta);
        }

        // POST: Respuestas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Respuestas == null)
            {
                return Problem("Entity set 'ForoContext.Respuestas'  is null.");
            }
            var respuesta = await _context.Respuestas.FindAsync(id);
            if (respuesta != null)
            {
                _context.Respuestas.Remove(respuesta);
            }
            
            await _context.SaveChangesAsync();
            return Redirect($"/preguntas/details/{respuesta.PreguntaId}");
        }

        private bool RespuestaExists(int id)
        {
          return _context.Respuestas.Any(e => e.RespuestaId == id);
        }
    }
}

Views/Preguntas/Create.cshtml
@model ORT_PNT1_Proyecto_2022_2C_I_Foro.Models.Pregunta

@{
    ViewData["Title"] = "Create";
}

<h1>Nueva Pregunta</h1>

<hr />
<div class="row">
    <div class="col-md-12">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
@*            <div class="form-group">
                <label asp-for="Fecha" class="control-label"></label>
                <input asp-for="Fecha" class="form-control" />
                <span asp-validation-for="Fecha" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <label asp-for="Titulo" class="control-label"></label>
                <input asp-for="Titulo" class="form-control" />
                <span asp-validation-for="Titulo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descripcion" class="control-label"></label>
                <textarea asp-for="Descripcion" class="form-control" style="resize:none;" rows="5"></textarea>
                <span asp-validation-for="Descripcion" class="text-danger"></span>
            </div>
@*            <div class="form-group">
                <label asp-for="CantMeGustas" class="control-label"></label>
                <input asp-for="CantMeGustas" class="form-control" />
                <span asp-validation-for="CantMeGustas" class="text-danger"></span>
            </div>*@
@*            <div class="form-group">
                <label asp-for="MiembroId" class="control-label"></label>
                <select asp-for="MiembroId" class ="form-control" asp-items="ViewBag.MiembroId"></select>
            </div>*@
            <div class="form-group">
                <input type="submit" value="Publicar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Volver</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Preguntas/Delete.cshtml
@model ORT_PNT1_Proyecto_2022_2C_I_Foro.Models.Pregunta

@{
    ViewData["Title"] = "Delete";
}

<h3>Seguro que quieres borrar esta pregunta?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Titulo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Titulo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Fecha)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Fecha)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Descripcion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CantMeGustas)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CantMeGustas)
        </dd>
        <dt class = "col-sm-2">
            Autor
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Miembro.NombreCompleto)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="PreguntaId" />
        <input type="submit" value="Borrar" class="btn btn-danger" /> |
        <a asp-action="Index">Volver</a>
    </form>
</div>

Views/Preguntas/Details.cshtml
@model ORT_PNT1_Proyecto_2022_2C_I_Foro.Models.Pregunta

@{
    ViewData["Title"] = "Detalles";
}

<h1>Pregunta: @Html.DisplayFor(model => model.Titulo)</h1>

<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Fecha)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Fecha)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Titulo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Titulo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Descripcion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CantMeGustas)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CantMeGustas)
        </dd>
        <dt class="col-sm-2">
            Autor
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Miembro.NombreCompleto)
        </dd>
        <dt class="col-sm-2">
            Respuestas
        </dt>
        <dd class="col-sm-10">
            <table class="table">
                <tr>
                    <th>Respuesta</th>
                    <th>Autor</th>
                    <th>Acciones</th>
                </tr>
                @foreach(var item in Model.Respuestas){
                    <tr>
                        <td>@Html.DisplayFor(m => item.Descripcion)</td>
                        <td>@Html.DisplayFor(m => item.Miembro.NombreCompleto)</td>
                        <td>
                        @if (Context.Session.GetString("_Rol") == "administrador" || Context.Session.GetInt32("_MiembroId") == item.MiembroId)
                        { 
                            <a asp-action="Delete" asp-controller="Respuestas" asp-route-id="@item.RespuestaId">Borrar</a>
                        }
                            </td>
                    </tr>
                }
            </table>
        </dd>
    </dl>
</div>
<div>
    @if (Context.Session.GetInt32("_MiembroId") != null){
        <span>
        <a asp-action="Create" asp-route-preguntaId=@Model.PreguntaId asp-route-titulo=@Model.Titulo asp-controller="Respuestas">Agregar Respuesta</a> |
        </span>
    }
    
    <a asp-action="Index">Volver</a>
</div>

Views/Preguntas/Index.cshtml
@model IEnumerable<ORT_PNT1_Proyecto_2022_2C_I_Foro.Models.Pregunta>

@{
    ViewData["Title"] = "Preguntas";
}

<div class="text-center main">

<h1 class="accent-font-color">Stack Underflow</h1>
<p>Preguntas de la comunidad, para la comunidad.</p>

    @if (Context.Session.GetInt32("_MiembroId") != null){
        <p>
            <a asp-action="Create" class="btn btn-primary" style="font-weight:500;">Publicar Nueva Pregunta</a>
        </p>
    }else{
        <p class="accent-font-color">Ingresá para preguntar!</p>
    }
@foreach(var item in Model){

    <div class="tarjeta">
        <div class="tarjeta-titulo">
                <h3>@Html.DisplayFor(modelItem => item.Titulo)</h3>
            @*<p class="tarjeta-categoria"><b>Categoria</b></p>*@
        </div>
        <div class="tarjeta-autor">
            <p class="autor">Por: @Html.DisplayFor(m => item.Miembro.NombreCompleto)</p>
            <p class="fecha">@Html.DisplayFor(m => item.Fecha)</p>
        </div>
        <p class="tarjeta-contenido">@Html.DisplayFor(m => item.Descripcion)</p>
        <div class="action-links">
            <a asp-action="Details" asp-route-id="@item.PreguntaId">Detalles</a> 
            @if(Context.Session.GetString("_Rol") == "administrador" || Context.Session.GetInt32("_MiembroId") == item.MiembroId ){
                <span>
                    | 
                <a asp-action="Delete" asp-route-id="@item.PreguntaId">Borrar</a>
                </span>
            }
        </div>
    </div>
}

</div>